# install codeserver by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure codeserver

- name: Create codeserver User
  user:
    name: codeserver
    shell: /usr/sbin/nologin
    home: /data/codeserver
    create_home: no

- name: Create codeserver directory
  file:
    path: /data/codeserver
    state: directory
    owner: codeserver
    group: codeserver
    
- name: Download&Setup codeserver
  shell: |
    cd /data/codeserver    
    curl -LO {{codeserver_download_url}}
    tar -xzvf code-server2.1692-vsc1.39.2-linux-x86_64.tar.gz
    cd code-server2.1692-vsc1.39.2-linux-x86_64
    cp code-server /usr/local/bin

- name: Create the storage directory for files.
  file:
    path: /var/lib/code-server
    state: directory 
    owner: codeserver 
    group: codeserver
    mode: '0755'

- name: Setting codeserver service
  template:
    src: code-server.service
    dest: /etc/systemd/system/code-server.service

- name: Restart codeserver
  shell: |
    systemctl enable code-server
    systemctl restart code-server


# set soft link, -f enforce the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /var/lib/code-server/logs  /data/codeserver


# check service state
- name: Check codeserver Service
  shell: systemctl status code-server | grep Active*
  register: check_codeserver_service
  notify: check_codeserver_service
