# install codeserver by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- block:
  - name: Check code-server Version
    #shell: sudo sh -c "docker inspect -f '{{ index .Config.Labels "build_version" }}' codeserver 1>> /data/logs/install_version.txt"
    shell: sudo sh -c "echo 'need test' 1>> /data/test"

- name: Check codeserver Service
  shell: docker inspect codeserver | grep Status
  register: check_codeserver_service
  notify: check_codeserver_service
